import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { ButtonType } from '../../typings';
import { getNextStates } from './gameAPI';

export interface ButtonsState {
  currentStep: ButtonType;
  histories: ButtonType[];
  availableSteps: ButtonType[];
  status: 'idle' | 'loading' | 'failed';
}

const initialState: ButtonsState = {
  currentStep: 'blue',
  histories: [],
  availableSteps: [],
  status: 'idle',
};

export type getAvailableStatesParams = {
  step: ButtonType;
  histories: ButtonType[];
}
export const getAvailableStatesAsync = createAsyncThunk(
  'counter/getEligibleNextStates',
  async ({ step, histories }: getAvailableStatesParams) => {
    const response = await getNextStates(step, histories);
    return {
      availableSteps: response.data
    }
  }
);

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    selectState: (state, action: PayloadAction<ButtonType>) => {
      state.histories = state.histories.length > 0 ?
        [state.histories[state.histories.length - 1], state.currentStep] :
        [state.currentStep];
      state.currentStep = action.payload;
      state.availableSteps = [];
    },
    reset: (state) => {
      state.currentStep = initialState.currentStep;
      state.histories = [];
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getAvailableStatesAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getAvailableStatesAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.availableSteps = action.payload.availableSteps;
      });
  },
});

export const { selectState, reset } = counterSlice.actions;

export const selectCurrentStep = (state: RootState) => state.game.currentStep;
export const selectAvailableSteps = (state: RootState) => state.game.availableSteps;
export const selectHistories = (state: RootState) => state.game.histories;
export const selectIsLoading = (state: RootState) => state.game.status === 'loading';

export default counterSlice.reducer;
